# Generated by Django 4.2.1 on 2023-05-03 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.PositiveBigIntegerField(blank=True, max_length=8, unique=True, verbose_name='D.N.I')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre/s')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido/s')),
                ('ciudad', models.CharField(max_length=30, verbose_name='Ciudad')),
                ('direccion', models.CharField(max_length=30, verbose_name='Direccion')),
                ('fecha_alta', models.DateField(blank=True, default=datetime.datetime(2023, 5, 3, 11, 32, 58, 336021), max_length=15, verbose_name='Fecha de alta')),
                ('estado', models.BooleanField(verbose_name='Ciudad')),
            ],
            options={
                'db_table': 'cliente',
                'ordering': ['id'],
            },
        ),
    ]
