# Generated by Django 4.2.1 on 2023-05-03 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.PositiveIntegerField(blank=True, unique=True, verbose_name='D.N.I'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_alta',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 3, 11, 35, 48, 528102), max_length=15, verbose_name='Fecha de alta'),
        ),
    ]
