# Generated by Django 4.2.1 on 2023-05-03 16:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0002_alter_cliente_dni_alter_cliente_fecha_alta'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
            ],
            options={
                'db_table': 'tipo_mascota',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.BooleanField(verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_alta',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 3, 13, 16, 15, 9664), max_length=15, verbose_name='Fecha de alta'),
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_chip', models.IntegerField(blank=True, unique=True, verbose_name='Numero de chip')),
                ('nombre_mascota', models.CharField(max_length=30, verbose_name='Nombre de mascota')),
                ('estado', models.BooleanField(verbose_name='Estado')),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veterinaria.cliente', verbose_name='propietario')),
                ('tipo_mascota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veterinaria.tipomascota', verbose_name='tipo de mascota')),
            ],
            options={
                'db_table': 'mascota',
                'ordering': ['id'],
            },
        ),
    ]
