# Generated by Django 4.2.1 on 2023-05-03 16:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0003_tipomascota_alter_cliente_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_alta',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 3, 13, 46, 34, 988928), max_length=15, verbose_name='Fecha de alta'),
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateField(blank=True, default=datetime.datetime(2023, 5, 3, 13, 46, 34, 988928), max_length=15, verbose_name='Fecha de consulta')),
                ('observaciones', models.CharField(max_length=500, verbose_name='Observaciones')),
                ('mascota_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veterinaria.mascota', verbose_name='mascota')),
            ],
            options={
                'db_table': 'historia_clinica',
                'ordering': ['id'],
            },
        ),
    ]
